### ISSUE TITLE
The latest npm (v1.2.0) is not sync with the latest code(now at tag v5.2.0)

### ISSUE THREAD

**Issue by hzwzw** [mattermost/mattermost-redux#613]
#### Summary
Issue in one concise sentence.

#### Environment Information
- mattermost/mattermost-redux

#### Steps to reproduce
The latest npm project [mattermost-redux](https://www.npmjs.com/package/mattermost-redux)(v1.2.0) is not sync with the latest code(now at tag v5.2.0).

#### Expected behavior
The npm project is sync with the github code or mention `Please don't use npm since they are not maintained` in Readme file.

Thank you! I want to mention that because it takes time to figure it out.

**Comment by shawn111** [comment]
Starting the app on PDAGAA4882006813 (/home/shawn/Android/Sdk/platform-tools/adb -s PDAGAA4882006813 shell am start -n com.mattermost.rnbeta/com.mattermost.rnbeta.MainActivity)...                
Starting: Intent { cmp=com.mattermost.rnbeta/.MainActivity }                                                                                                                                       
Error type 3                                                                                                                                                                                       
Error: Activity class {com.mattermost.rnbeta/com.mattermost.rnbeta.MainActivity} does not exist.                                                                                                   
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)BUILDING MODULES FOR android                                                                                                         
error: bundling failed: Error: Unable to resolve module `mattermost-redux/utils/event_emitter` from `/home/shawn/js/mattermost-mobile/app/mattermost.js`: Module `mattermost-redux/utils/event_emi$
ter` does not exist in the Haste module map                                                                                                                                                        
                                                                                                                                                                                                   
This might be related to https://github.com/facebook/react-native/issues/4968                                                                                                                      
To resolve try the following:                                                                                                                                                                      
  1. Clear watchman watches: `watchman watch-del-all`.                                                                                                                                             
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.                                                                                                                       
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.                                                                                               
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.                                                                                                                          
    at ModuleResolver.resolveDependency (/home/shawn/js/mattermost-mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:209:1301)                                          
    at ResolutionRequest.resolveDependency (/home/shawn/js/mattermost-mobile/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:83:16)                                         
    at DependencyGraph.resolveDependency (/home/shawn/js/mattermost-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:238:485)                                                           
    at Object.resolve (/home/shawn/js/mattermost-mobile/node_modules/metro/src/lib/transformHelpers.js:180:25)                                                                                     
    at dependencies.map.result (/home/shawn/js/mattermost-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:311:29)                                                               
    at Array.map (<anonymous>)                                                                                                                                                                     
    at resolveDependencies (/home/shawn/js/mattermost-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:307:16)                                                                   
    at /home/shawn/js/mattermost-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:164:33                                                                                         
    at Generator.next (<anonymous>)                                                                                                                                                                
    at step (/home/shawn/js/mattermost-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:266:307) 

Not sure is it the same issue.


Here are my steps:
1. git clone https://github.com/mattermost/mattermost-mobile
2. cd mattermost-mobile
3. npm install
3.a pushd node_modules/mattermost-redux;npm install; popd # to avoid the dependency issue.
4. react-native run-android

**Comment by hanzei** [comment]
Thanks for the report @hzwzw.

This projects is released alongside the server releases since 5.3.1. See e.g. https://www.npmjs.com/package/mattermost-redux/v/5.5.0
